/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './app/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        life: '#10B981',
        'life-light': '#D1FAE5',
        'life-dark': '#059669',
        work: '#3B82F6',
        'work-light': '#DBEAFE',
        'work-dark': '#2563EB',
        urgent: '#EF4444',
        high: '#F97316',
        normal: '#6B7280',
        low: '#9CA3AF',
        someday: '#D1D5DB',
        surface: '#F9FAFB',
        'surface-2': '#F3F4F6',
        border: '#E5E7EB',
        'text-primary': '#111827',
        'text-secondary': '#6B7280',
        'text-tertiary': '#9CA3AF',
      },
      fontFamily: {
        pretendard: ['Pretendard', 'System'],
        inter: ['Inter', 'System'],
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
      },
      borderRadius: {
        sm: '4px',
        DEFAULT: '8px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
